export const Genres = {
  "action": "Action",
  "adult-cast": "Adult Cast",
  "adventure": "Adventure",
  "anthropomorphic": "Anthropomorphic",
  "avant-garde": "Avant Garde",
  "boys-love": "Boys Love",
  "cgdct": "CGDCT",
  "cars": "Cars",
  "childcare": "Childcare",
  "comedy": "Comedy",
  "comic": "Comic",
  "crime": "Crime",
  "crossdressing": "Crossdressing",
  "delinquents": "Delinquents",
  "dementia": "Dementia",
  "demons": "Demons",
  "detective": "Detective",
  "drama": "Drama",
  "dub": "Dub",
  "ecchi": "Ecchi",
  "erotica": "Erotica",
  "family": "Family",
  "fantasy": "Fantasy",
  "gag-humor": "Gag Humor",
  "game": "Game",
  "gender-bender": "Gender Bender",
  "gore": "Gore",
  "gourmet": "Gourmet",
  "harem": "Harem",
  "high-stakes-game": "High Stakes Game",
  "historical": "Historical",
  "horror": "Horror",
  "isekai": "Isekai",
  "iyashikei": "Iyashikei",
  "josei": "Josei",
  "kids": "Kids",
  "magic": "Magic",
  "magical-sex-shift": "Magical Sex Shift",
  "mahou-shoujo": "Mahou Shoujo",
  "martial-arts": "Martial Arts",
  "mecha": "Mecha",
  "medical": "Medical",
  "military": "Military",
  "music": "Music",
  "mystery": "Mystery",
  "mythology": "Mythology",
  "organized-crime": "Organized Crime",
  "parody": "Parody",
  "performing-arts": "Performing Arts",
  "pets": "Pets",
  "police": "Police",
  "psychological": "Psychological",
  "racing": "Racing",
  "reincarnation": "Reincarnation",
  "romance": "Romance",
  "romantic-subtext": "Romantic Subtext",
  "samurai": "Samurai",
  "school": "School",
  "sci-fi": "Sci-Fi",
  "seinen": "Seinen",
  "shoujo": "Shoujo",
  "shoujo-ai": "Shoujo Ai",
  "shounen": "Shounen",
  "shounen-ai": "Shounen Ai",
  "showbiz": "Showbiz",
  "slice-of-life": "Slice of Life",
  "space": "Space",
  "sports": "Sports",
  "strategy-game": "Strategy Game",
  "super-power": "Super Power",
  "supernatural": "Supernatural",
  "survival": "Survival",
  "suspense": "Suspense",
  "team-sports": "Team Sports",
  "thriller": "Thriller",
  "time-travel": "Time Travel",
  "vampire": "Vampire",
  "visual-arts": "Visual Arts",
  "work-life": "Work Life",
  "workplace": "Workplace",
  "yaoi": "Yaoi",
  "yuri": "Yuri"
}


