export const Genres = {
  action: "Action",
  adventure: "Adventure",
  cars: "Cars",
  comedy: "Comedy",
  dementia: "Dementia",
  demons: "Demons",
  drama: "Drama",
  ecchi: "Ecchi",
  fantasy: "Fantasy",
  game: "Game",
  harem: "Harem",
  historical: "Historical",
  horror: "Horror",
  josei: "Josei",
  kids: "Kids",
  magic: "Magic",
  martial_arts: "Martial Arts",
  mecha: "Mecha",
  military: "Military",
  music: "Music",
  mystery: "Mystery",
  parody: "Parody",
  police: "Police",
  psychological: "Psychological",
  romance: "Romance",
  samurai: "Samurai",
  school: "School",
  sci_fi: "Sci-Fi",
  seinen: "Seinen",
  shoujo: "Shoujo",
  shoujo_ai: "Shoujo Ai",
  shounen: "Shounen",
  shounen_ai: "Shounen Ai",
  slice_of_life: "Slice of Life",
  space: "Space",
  sports: "Sports",
  super_power: "Super Power",
  supernatural: "Supernatural",
  thriller: "Thriller",
  vampire: "Vampire",
  yaoi: "Yaoi",
  yuri: "Yuri",
};
